[build]
  # أمر البناء
  command = "npm run build"
  
  # مجلد المخرجات
  publish = "dist"

# إعادة التوجيه للصفحات (SPA routing)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers للأمان والأداء
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache للملفات الثابتة
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

